/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2025-03-11 16:03:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.Map;

public final class viewNotes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Notes</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<form action=\"allNotesServlet?sortId\" method=\"post\">\n");
      out.write("    <input type=\"hidden\" name=\"sortId\" value=\"0\">\n");
      out.write("    <button type=\"submit\">Sort by Date Added</button>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<h2>All Notes</h2>\n");
      out.write("<ul>\n");
      out.write("    ");

        List<Map<String, String>> allNotes = (List<Map<String, String>>) request.getAttribute("allNotes");
        for (Map<String, String> noteContent : allNotes){
            String name = noteContent.get("name");
            System.out.println("NoteId from HTML" + name);
            String text = noteContent.get("text");
            String url = noteContent.get("url");
            if (text!=null){
                text = text.replaceAll("(https?://[^\s]+)", "<a href=\"$1\" target=\"_blank\">$1</a>)");
            }
            else {
                text = "";
            }
    
      out.write("\n");
      out.write("    <div style=\"border: 1px solid blueviolet; padding: 10px; margin-bottom: 20px;\">\n");
      out.write("        <h2 id=\"titleName_");
      out.print(name);
      out.write("\" onclick=\"document.getElementById('newTitleForm_");
      out.print(name);
      out.write("').style.display='block'; document.getElementById('hideTitleForm_");
      out.print(name);
      out.write("').style.display='block'\">");
      out.print(name);
      out.write("</h2>\n");
      out.write("        <form id=\"newTitleForm_");
      out.print(name);
      out.write("\" action=\"editNoteServlet?noteId=");
      out.print(name);
      out.write("&editType=");
      out.print(0);
      out.write("\" method=\"post\" style=\"display:none;\">\n");
      out.write("            <label type=\"hidden\" for=\"newContent_");
      out.print(name);
      out.write("\">Rename</label>\n");
      out.write("            <input id=\"newContent_");
      out.print(name);
      out.write("\" name=\"newContent\" type=\"text\">\n");
      out.write("            <button type=\"submit\">\n");
      out.write("                Submit\n");
      out.write("            </button>\n");
      out.write("        </form>\n");
      out.write("        <button id=\"hideTitleForm_");
      out.print(name);
      out.write("\" type=\"submit\" onclick=\"document.getElementById('newTitleForm_");
      out.print(name);
      out.write("').style.display='none';document.getElementById('hideTitleForm_");
      out.print(name);
      out.write("').style.display='none'\" style=\"display:none;\">\n");
      out.write("            Hide\n");
      out.write("        </button>\n");
      out.write("        <p id=\"textBox_");
      out.print(name);
      out.write("\" onclick=\"document.getElementById('editTextForm_");
      out.print(name);
      out.write("').style.display='block'\">");
      out.print(text);
      out.write(" <a href=\"");
      out.print(url);
      out.write('"');
      out.write('>');
      out.print(url);
      out.write("</a> </p>\n");
      out.write("        <form id=\"editTextForm_");
      out.print(name);
      out.write("\" action=\"editNoteServlet?noteId=");
      out.print(name);
      out.write("&editType=");
      out.print(1);
      out.write("\" method=\"post\" style=\"display:none;\">\n");
      out.write("            <label type=\"hidden\" for=\"newContent_");
      out.print(name);
      out.write("\">Edit:</label>\n");
      out.write("            <input id=\"editText_");
      out.print(name);
      out.write("\" name=\"newContent\" type=\"text\">\n");
      out.write("            <button type=\"submit\">\n");
      out.write("                Submit\n");
      out.write("            </button>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("    ");

        }
    
      out.write("\n");
      out.write("</ul>\n");
      out.write("<ul>\n");
      out.write("    <a href=\"createNote.jsp\">New Note</a>\n");
      out.write("    <br>\n");
      out.write("    <br>\n");
      out.write("    <a href=\"index.html\">Back to Home</a>\n");
      out.write("</ul>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
